### ISSUE TITLE
whereis lookup logic is wrong

### ISSUE THREAD

**Issue by techtonik** [vvo/node-whereis#4]
The package should not fallback on `whereis` if `which` failed on Linux. See https://github.com/vvo/selenium-standalone/issues/96 for the example of mislocating java binary by trusting `whereis`.

See https://superuser.com/questions/40301/which-whereis-differences for the explanation of `whereis` command. It should come with additional checks to get binaries correctly.

**Comment by vvo** [comment]
I am happy to take a PR on this @techtonik

**Comment by techtonik** [comment]
Not sure it will happen any time soon. As I don't code in JavaScript, there is bigger issue with understanding the whole Gratipay JS testing toolchai, and it will just take more time for me than for somebody who knows how `npm` works and deal with it daily.

**Comment by vvo** [comment]
@techtonik I think using https://github.com/isaacs/node-which is the way to go
